---
- hosts: oci-instances
  vars:
    install_portainer: false
    install_traefik_and_portainer: true
  roles:
    - role: ansible-docker-engine
    - role: ansible-swapfile
      become: true
    - role: ansible-docker-container-portainer
      when: install_portainer | bool
    - role: ansible-docker-containers
      when: install_traefik_and_portainer | bool
