---
- hosts: oci-instances
  vars:
    install_portainer: true
  roles:
    - role: ansible-docker-engine
    - role: ansible-swapfile
      become: true
    - role: ansible-docker-container-portainer
      when: install_portainer | bool
