---
# defaults file for ansible-docker-engine

docker_edition: "ce"

docker_version: ""

docker_channel: ["stable"]

docker_state: "present"

docker_users: 
  - ubuntu

docker_package_dependencies:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
  
docker_architecture_map:
  "x86_64": "amd64"
  "aarch": "arm64"
  "armhf": "armhf"
  "armv7l": "armhf"

docker_apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

docker_apt_key_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

docker_apt_repository: >
  deb [arch={{ docker_architecture_map[ansible_architecture] }}]
  https://download.docker.com/linux/{{ ansible_distribution | lower }}
  {{ ansible_distribution_release }} {{ docker_channel | join (' ') }}
